### ISSUE TITLE
Сайт conf.in.ua не работает

### ISSUE THREAD

**Issue by askertv** [yiiframework-ua/conf.in.ua#1]
> 503 Service Temporarily Unavailable
> nginx

**Comment by Borales** [comment]
@askertv там пока что ничего и нету.

**Comment by askertv** [comment]
Понятно. Ну, можно же редирект на какой нибудь свой другой сайт сделать, либо вывести надпись "Under construction"? Сайт с ошибкой, не красиво выглядит как для пользователей, так и для поисковиков.

**Comment by Borales** [comment]
Добавлена страница-заглушка (возможно днс еще обновляется)

**Comment by askertv** [comment]
Норм. Отлично)
